### PR TITLE
Support self-hosted usage

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Use `this.baseUrl` to allow for querying self-hosted versions of quickchart

### CODE REVIEW

**Comment by typpo** [comment]
Thank you!  I've made a change to getShortUrl() to throw when used with a non-quickchart host.  Unfortunately the self-hosted version doesn't support right now because it requires an external database.

**Comment by typpo** [comment]
Published to npm in v1.0.8

**Comment by cheerfulstoic** [comment]
😕  I changed two places because I found two places, but maybe the change inside of `toBinary` should stay?  I'm currently using my branch in our development environment and it's working fine to query the self-hosted quickchart app.  I haven't used `getShortUrl`, so I can believe that it wouldn't work there

**Comment by cheerfulstoic** [comment]
Oh, nevermind, I see!  When I clicked into the PR I just saw your commit.  Thanks for releasing it!

**Pull request merged**
